platform :ios, '8.0'
target ‘MultipleColumns’ do

pod 'AFNetworking', '~> 3.1.0'

pod 'SDWebImage', '~> 4.0.0'

pod 'SDAutoLayout', '~> 2.1.3'

pod 'MBProgressHUD', '~> 1.0.0'

pod 'RESideMenu', '~> 4.0.7'

pod 'Masonry', '~> 1.0.2'

pod 'YYModel', '~> 1.0.4'

end
